name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start MongoDB for tests
        uses: supercharge/mongodb-github-action@1.3.0
      - name: Test with pytest
        run: python -m pytest tests --junit-xml pytest.xml
        env:
          API_KEY: ${{ secrets.WORDNIK_API_KEY }}
          DB_HOST: localhost
          DB_PORT: 27017
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: pytest.xml
          check_name: Test results
